services:
    mongo-nota:
        image: mongo
        container_name: mongo-nota
        ports:
            - "27017:27017"
        volumes:
            - mongo-nota-data:/data/db
        healthcheck:
            test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            retries: 5
            start_period: 10s
            timeout: 5s
        networks: 
            - nota

    rabbitmq:
        image: rabbitmq:4.0-management
        container_name: rabbitmq
        ports:
            - "5672:5672"  # Port cho giao thức AMQP
            - "15672:15672"  # Port cho giao diện quản trị web RabbitMQ
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 5s
        networks:
            - nota

    mongo-nota-express:
        image: mongo-express
        container_name: mongo-nota-express
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_URL=mongodb://mongo-nota:27017/
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
        networks: 
            - nota

    auth-service:
        image: hieuphamorigin/src-auth-service:latest
        container_name: auth-service
        ports:
            - "3001:3001"
        depends_on:
            rabbitmq:
                condition: service_healthy
        restart: always
        environment:
            - MONGO_URI_FLIGHT=mongodb://mongo-nota:27017/users
            - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:3001 || exit 1"]
            interval: 10s
            retries: 5
            start_period: 20s
            timeout: 5s
        networks: 
            - nota
 
    note-service:
        container_name: note_service
        image: lochoang174/note-service:latest
        ports:
            - 3002:3002
        environment:
            - MONGO_URI_FLIGHT=mongodb://mongo-nota:27017/notes
            - JWT_ACCESS=ACCESS_API
            
        depends_on:
            rabbitmq:
                condition: service_healthy
        links: 
            - rabbitmq
        networks:
            - nota

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        networks:
            - nota
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"

        depends_on:
            - auth-service
            - note-service
            - frontend-service

    frontend-service:
        build: frontend/
        # image: lamtruongphu/frontend-service:latest
        container_name: frontend-service
        ports:
            - "5173:5173"
        depends_on:
            - auth-service
            - note-service
        environment:
            - VITE_SERVER=http://localhost
        networks: 
            - nota
        
volumes:
  mongo-nota-data:

networks:
    nota:
        driver: bridge